name: Linux Experimental Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        qt: [ qt5, qt6 ]
        exclude:
          - os: ubuntu-22.04
            # libqscintilla2-qt6-dev not packaged
            qt: qt6

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} ${{ matrix.qt }}

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.qt }}
        max-size: "500M"
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      run: |
        which sudo || ( apt update && apt install -y sudo )
        sudo -E ./scripts/uni-get-dependencies.py --yes --profile pythonscad-${{ matrix.qt }}
    - name: Install gcovr
      run: python -m pip install -U gcovr
    - name: Build and test
      env:
        CMAKE_CXX_COMPILER_LAUNCHER: ccache
        CMAKE_C_COMPILER_LAUNCHER: ccache
      run: ./scripts/github-ci.sh experimental enable_python ${{ matrix.qt == 'qt6' && 'qt6' || '' }} build test coverage
    - name: Show ccache statistics
      run: ccache -s
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v5
      if: ${{ always() }}
      with:
        name: Test Result Report (${{ matrix.os }} ${{ matrix.qt }})
        path: |
          b/Testing/Temporary/*_report.html
          b/Testing/Temporary/LastTest.log
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v5
      with:
        name: Code Coverage Report (${{ matrix.os }} ${{ matrix.qt }})
        path: c/coverage*.html
